export default {
  REQUEST_MOVIE_SUCCESS: 'MOVIE/REQUEST_MOVIE_SUCCESS',
  REQUEST_MOVIE_ERROR: 'MOVIE/REQUEST_MOVIE_ERROR',
  REQUEST_MOVIE: 'MOVIE/REQUEST_MOVIE',
  CLEAR_MOVIE_STORE: 'MOVIE/CLEAR_MOVIE_STORE'
}